---
# tasks file for ghostfolio
- name: Create ghostfolio folder
  file:
    path: "/home/{{ user_name }}/docker/ghostfolio"
    state: directory

- name: Template docker-compose file to target
  template:
    src: "docker-compose.yml.j2"
    dest: "/home/{{ user_name }}/docker/ghostfolio/docker-compose.yml"

- name: Template .env configuration
  template:
    src: ".env.j2"
    dest: "/home/{{ user_name }}/docker/ghostfolio/.env"

- name: Deploy ghostfolio
  docker_compose:
    project_src: /home/{{ user_name }}/docker/ghostfolio
    state: present
    pull: true
