---

- name: Bonsai-Stack
  hosts: kf-orc-arm-02
  serial: 10
  roles:
    - monitoring/bonsai/bonsai-stack

- name: Bonsai-Exporter
  hosts: all
  serial: 10
  roles:
    - monitoring/bonsai/bonsai-exporter