---

- name: Web-remote
  hosts: kf-orc-arm-01
  serial: 10
  roles:
    - services/proxy/fail2ban

- name: Web-local
  hosts: kf-opt-salmon-01
  serial: 10
  roles:
    - services/proxy/fail2ban
    