---

- name: Oracle-pre
  hosts: oracle
  serial: 10
  roles:
    - setup/basic-setup-oracle

- name: Main
  hosts: all
  serial: 10
  roles:
    - geerlingguy.docker
    - setup/basic-setup

    - cloudalchemy.node_exporter
    - monitoring/exporters/cadvisor
    - monitoring/bonsai/bonsai-exporter

- name: Bitwarden
  hosts: kf-orc-amd-02
  roles:
    - services/bitwarden

#- name: Media
#  hosts: kf-opt-salmon-01
#  roles:
#    - services/media/plex
#    - services/media/jellyfin

- name: Medfish
  hosts: kf-opt-tuna-01
  roles:
    - services/media/medfish

- name: Monitoring
  hosts: kf-orc-arm-02
  serial: 10
  roles:
    - monitoring/portainer
    - monitoring/exporters/fortigate-exporter
    - monitoring/grafana-stack

    - monitoring/bonsai/bonsai-stack

- name: Pocketbase
  hosts: kf-orc-arm-01
  roles:
    - role: services/pocketbase
      pocketbase_name: "sudoku"

- name: Web-remote
  hosts: kf-orc-arm-01
  serial: 10
  roles:
    - services/proxy/cloudflare-dns
    - services/proxy/certbot
    - services/proxy/fail2ban
    - services/proxy/nginx-remote
    - services/streaks-api


- name: Web-local
  hosts: kf-opt-salmon-01
  serial: 10
  roles:
    - services/proxy/cloudflare-dns
    - services/proxy/nginx-local
    - services/proxy/fail2ban
