---

- name: Create promtail folder
  file:
    path: "/home/{{ user_name }}/docker/exporters/promtail"
    state: directory

- name: Create promtail tmp folder
  file:
    path: "/home/{{ user_name }}/docker/exporters/promtail/tmp"
    state: directory

- name: Template docker-compose file
  template:
    src: "docker-compose.yml.j2"
    dest: "/home/{{ user_name }}/docker/exporters/promtail/docker-compose.yml"

- name: Check if Nginx access log exists
  ansible.builtin.stat:
    path: /var/log/nginx/access.log
  register: nginx_access_log

- name: Template Promtail config for nginx
  template:
    src: promtail.yml.j2
    dest: "/home/{{ user_name }}/docker/exporters/promtail/promtail.yml"

- name: Deploy promtail
  docker_compose:
    project_src: /home/{{ user_name }}/docker/exporters/promtail
    state: present
    pull: true
    recreate: smart
    restarted: true
