---

- name: Create bonsai_exporter directory
  file:
    path: /home/{{ user_name }}/docker/bonsai_exporter
    state: directory

- name: Template docker-compose file
  template:
    src: "docker-compose.yml.j2"
    dest: "/home/{{ user_name }}/docker/bonsai_exporter/docker-compose.yml"

- name: Template bonsai config file
  template:
    src: "bonsai-config.yaml.j2"
    dest: "/home/{{ user_name }}/docker/bonsai_exporter/config-ansible.yaml"

- name: Deploy bonsai exporter
  docker_compose:
    project_src: /home/{{ user_name }}/docker/bonsai_exporter
    state: present
    pull: true