---
# tasks file for certbot

- name: Install certbot
  apt:
    name: python3-certbot

- name: Install certbot-dns-cloudflare
  apt:
    name: python3-certbot-dns-cloudflare

- name: Create /etc/letsencrypt
  file: 
    path: /etc/letsencrypt 
    state: directory
    recurse: yes

- name: Template cloudflare.ini
  template: 
    src: cloudflare.ini.j2 
    dest: /etc/letsencrypt/cloudflare.ini

- name: Get current certificate
  community.crypto.get_certificate:
    host: "grafana.konst.fish"
    port: 443
  run_once: true
  register: cert

- name: Check how many days cert is still valid for
  debug:
    msg: "cert expires in: {{ expire_days }} days."
  vars:
    expire_days: "{{ (( cert.not_after | to_datetime('%Y%m%d%H%M%SZ')) - (ansible_date_time.iso8601 | to_datetime('%Y-%m-%dT%H:%M:%SZ')) ).days }}"


- block:
  - name: Run certbot
    command: certbot certonly --dns-cloudflare --dns-cloudflare-credentials /etc/letsencrypt/cloudflare.ini --email '{{ letsencrypt_email }}' --domain '*.{{ fqdn }}' --agree-tos --non-interactive
  vars:
    expire_days: "{{ (( cert.not_after | to_datetime('%Y%m%d%H%M%SZ')) - (ansible_date_time.iso8601 | to_datetime('%Y-%m-%dT%H:%M:%SZ')) ).days }}"
  when: expire_days|int < 15


- name: Fetch letsencrypt cert to local
  synchronize:
    src: /etc/letsencrypt
    dest: buffer/
    mode: pull
  when: inventory_hostname == 'kf-orc-arm-01'
