---
# tasks file for basic-setup

- name: Install fail2ban
  apt:
    name: fail2ban
    state: present

- name: Enable and start fail2ban service
  systemd:
    name: fail2ban
    enabled: yes
    state: started

- name: Template jail.local.j2
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
  notify: Restart fail2ban service

- name: Copy filters
  copy:
    src: filters/
    dest: /etc/fail2ban/filter.d/
  notify: Restart fail2ban service

## exporter
- name: Create fail2ban-exporter folder
  file:
    path: "/home/{{ user_name }}/docker/fail2ban-exporter/"
    state: directory
  
- name: Template docker-compose.yml
  template:
    src: "docker-compose.yml.j2"
    dest: "/home/{{ user_name }}/docker/fail2ban-exporter/docker-compose.yml"

- name: Deploy fail2ban-exporter
  docker_compose:
    project_src: /home/{{ user_name }}/docker/fail2ban-exporter/
    state: present
    build: true

- meta: flush_handlers
