version: '3'

services:
  bitwarden:
    image: vaultwarden/server:latest
    volumes:
      - ./bwdata:/data
    environment:
      - SIGNUPS_ALLOWED=false
    restart: on-failure

  nginx:
    image: nginx:1.15-alpine
    ports:
      - "30013:3000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
