{
 "title": "Main",
 "tags": [
  "linux",
  "docker"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_Prometheus", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "node" },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"$node:9100\", job=~\"$job\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=\"$node:9100\", job=~\"$job\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{instance=\"$node:9100\", job=~\"$job\"}) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MEM",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"$node:9100\",job=~\"$job\"} * 100) / node_memory_MemTotal_bytes{instance=\"$node:9100\",job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=\"$node:8080\",name=~\".*\",name=~\".+\"}[5m])) by (name) *100",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}