---
# tasks file for medfish

- name: Create medfish folder
  file:
    path: "/home/{{ user_name }}/docker/medfish"
    state: directory

- name: Template docker-compose file
  template:
    src: "docker-compose.yml.j2"
    dest: "/home/{{ user_name }}/docker/medfish/docker-compose.yml"

- name: Deploy medfish stack
  docker_compose:
    project_src: /home/{{ user_name }}/docker/medfish
    state: present
    pull: true
    #restarted: true

