{
 "title": "Fortigate Exporter",
 "description": "A Dashboard for the Prometheus fortigate_exporter",
 "tags": [
  "prometheus",
  "fortigate"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_Prometheus", "label": "Datasource", "query": "prometheus" },
   { "name": "firewall", "query": { "query": "fortigate_version_info" } },
   {
    "name": "scope",
    "query": {
     "query": "fortigate_certificate_info{instance=~\"[[firewall]]\"}"
    }
   },
   {
    "name": "vdom",
    "query": {
     "query": "fortigate_certificate_info{instance=~\"[[firewall]]\"}"
    }
   },
   {
    "name": "interface",
    "label": "interface",
    "query": {
     "query": "label_values(fortigate_interface_link_up{instance=\"[[firewall]]\"}, name)"
    }
   },
   {
    "name": "phase1",
    "query": {
     "query": "fortigate_ipsec_tunnel_up{instance=~\"[[firewall]]\"}"
    }
   },
   {
    "name": "phase2",
    "query": {
     "query": "fortigate_ipsec_tunnel_up{instance=~\"[[firewall]]\"}"
    }
   },
   {
    "name": "monitor",
    "query": {
     "query": "fortigate_link_status_change_time_seconds{instance=~\"[[firewall]]\"}"
    }
   },
   {
    "name": "sdwan",
    "query": {
     "query": "fortigate_virtual_wan_status{instance=~\"[[firewall]]\"}"
    }
   },
   {
    "name": "certificate",
    "query": {
     "query": "fortigate_certificate_info{instance=~\"[[firewall]]\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "fortigate_version_info{instance=~\"[[firewall]]\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "VPN Clients",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fortigate_vpn_connections{instance=~\"[[firewall]]\"}",
     "legendFormat": "VPN Clients"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "fortigate_memory_usage_ratio{instance=~\"[[firewall]]\"} * 100"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 1 },
   "yaxes": [
    { "format": "percent", "label": "Percent" }
   ],
   "targets": [
    {
     "expr": "fortigate_cpu_usage_ratio{instance=~\"[[firewall]]\"} *100",
     "legendFormat": "CPU{{processor}}"
    }
   ]
  },
  {
   "title": "VDOM Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "VDOM" }
   ],
   "targets": [
    {
     "expr": "fortigate_license_vdom_usage{instance=~\"[[firewall]]\"}",
     "legendFormat": "VDOMs"
    },
    {
     "expr": "fortigate_license_vdom_max\r{instance=~\"[[firewall]]\"}",
     "legendFormat": "VDOM Max"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Sessions" }
   ],
   "targets": [
    {
     "expr": "fortigate_current_sessions{instance=~\"[[firewall]]\"}",
     "legendFormat": "{{protocol}} Sessions"
    }
   ]
  },
  {
   "title": "Policies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Policy Active Sessions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none", "label": "Sessions" }
   ],
   "targets": [
    {
     "expr": "rate(fortigate_policy_active_sessions{instance=~\"[[firewall]]\"}[5m])",
     "legendFormat": "id:{{id}}"
    }
   ]
  },
  {
   "title": "Policy Hit Cound Total",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "none", "label": "Hit count" }
   ],
   "targets": [
    {
     "expr": "rate(fortigate_policy_hit_count_total{instance=~\"[[firewall]]\"}[5m])",
     "legendFormat": "id:{{id}}"
    }
   ]
  },
  {
   "title": "Policy Bytes Total",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "decbytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "rate(fortigate_policy_bytes_total{instance=~\"[[firewall]]\"}[5m])",
     "legendFormat": "id:{{id}}"
    }
   ]
  },
  {
   "title": "Policy Packets Total",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(fortigate_policy_packets_total{instance=~\"[[firewall]]\"}[5m])",
     "legendFormat": "id:{{id}}"
    }
   ]
  },
  {
   "title": "VPN",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Client VPN Connections",
   "type": "graph",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fortigate_vpn_connections{instance=~\"[[firewall]]\",vdom=~\"[[vdom]]\"}",
     "legendFormat": "Client VPN connections"
    }
   ]
  },
  {
   "title": "IPsec VPN status",
   "type": "table-old",
   "gridPos": { "h": 13, "w": 6, "x": 15, "y": 25 },
   "targets": [
    {
     "expr": "fortigate_ipsec_tunnel_up{instance=\"[[firewall]]\"}",
     "legendFormat": "{{parent}} / {{name}}"
    }
   ]
  },
  {
   "title": "[[phase2]] Bandwidth",
   "type": "graph",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 29 },
   "repeat": "phase2",
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(fortigate_ipsec_tunnel_receive_bytes_total{instance=\"[[firewall]]\",parent=~\"[[phase1]]\",name=~\"[[phase2]]\"}[5m]) * 8",
     "legendFormat": "{{name}} receive"
    },
    {
     "expr": "rate(fortigate_ipsec_tunnel_receive_bytes_total{instance=\"[[firewall]]\",parent=~\"[[phase1]]\",name=~\"[[phase2]]\"}[5m]) * 8\r\n",
     "legendFormat": "{{name}} transmit"
    }
   ]
  },
  {
   "title": "Interface",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {}
   ]
  },
  {
   "title": "[[interface]] Bandwidth",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 39 },
   "repeat": "interface",
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(fortigate_interface_receive_bytes_total{instance=\"[[firewall]]\",name=\"[[interface]]\"}[5m]) * 8",
     "legendFormat": "Receive"
    },
    {
     "expr": "irate(fortigate_interface_transmit_bytes_total{instance=\"[[firewall]]\",name=\"[[interface]]\"}[5m]) * 8\r\n",
     "legendFormat": "Send"
    }
   ]
  },
  {
   "title": "Transmit Packets",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 59 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(fortigate_interface_transmit_packets_total{instance=~\"[[firewall]]\",name=~\"[[interface]]\"}[5m])",
     "legendFormat": "[[interface]] transmit"
    },
    {
     "expr": "irate(fortigate_interface_receive_packets_total{instance=~\"[[firewall]]\",name=~\"[[interface]]\"}[5m])",
     "legendFormat": "[[interface]] receive"
    }
   ]
  },
  {
   "title": "[[interface]] Errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(fortigate_interface_transmit_errors_total{instance=~\"[[firewall]]\",name=\"[[interface]]\"}[5m])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "rate(fortigate_interface_receive_errors_total{instance=~\"[[firewall]]\",name=\"[[interface]]\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Interface status",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "fortigate_interface_speed_bps{instance=~\"[[firewall]]\"}",
     "legendFormat": "{{name}} "
    }
   ]
  },
  {
   "title": "Link monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Link Status",
     "type": "graph",
     "gridPos": { "h": 5, "w": 7, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "fortigate_interface_link_up{instance=~\"[[firewall]]\"} != 0\r\n",
       "legendFormat": "{{monitor}}"
      }
     ]
    },
    {
     "title": "Link Latency",
     "type": "graph",
     "gridPos": { "h": 5, "w": 7, "x": 7, "y": 17 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "fortigate_link_latency_seconds{instance=~\"[[firewall]]\"}\r\n",
       "legendFormat": "{{monitor}}"
      }
     ]
    },
    {
     "title": "Link Packets Sent / Received Total",
     "type": "graph",
     "gridPos": { "h": 5, "w": 7, "x": 14, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "fortigate_link_packet_sent_total{instance=~\"[[firewall]]\"}\r",
       "legendFormat": "{{monitor}} sent"
      },
      {
       "expr": "fortigate_link_packet_received_total{instance=~\"[[firewall]]\"}",
       "legendFormat": "{{monitor}} received"
      }
     ]
    },
    {
     "title": "[[monitor]] State Change",
     "type": "stat",
     "gridPos": { "h": 2, "w": 7, "x": 0, "y": 22 },
     "repeat": "monitor",
     "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "fortigate_link_status_change_time_seconds{instance=~\"[[firewall]]\",monitor=\"[[monitor]]\"} *1000",
       "legendFormat": "{{monitor}}"
      }
     ]
    },
    {
     "title": "Link Jitter",
     "type": "graph",
     "gridPos": { "h": 5, "w": 7, "x": 7, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "fortigate_link_latency_jitter_seconds{instance=~\"[[firewall]]\"}\r",
       "legendFormat": "{{monitor}}"
      }
     ]
    },
    {
     "title": "Link Active Sessions",
     "type": "graph",
     "gridPos": { "h": 5, "w": 7, "x": 14, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "fortigate_link_active_sessions{instance=~\"[[firewall]]\"}\r",
       "legendFormat": "{{monitor}}"
      }
     ]
    },
    {
     "title": "Link Packet Loss",
     "type": "graph",
     "gridPos": { "h": 5, "w": 7, "x": 7, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "fortigate_link_packet_loss_ratio{instance=~\"[[firewall]]\"}\r",
       "legendFormat": "{{monitor}}"
      }
     ]
    },
    {
     "title": "[[monitor]] Bandwidth",
     "type": "graph",
     "gridPos": { "h": 4, "w": 7, "x": 14, "y": 27 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "irate(fortigate_link_bandwidth_tx_byte_per_second{instance=\"[[firewall]]\",monitor=~\"[[monitor]]\"}[1m]) * 8",
       "legendFormat": "{{monitor}} TX"
      },
      {
       "expr": "irate(fortigate_link_bandwidth_rx_byte_per_second{instance=\"[[firewall]]\",monitor=~\"[[monitor]]\"}[1m]) * 8\r",
       "legendFormat": "{{monitor}} RX"
      }
     ]
    }
   ]
  },
  {
   "title": "Certificate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Certificate expiry date",
     "type": "stat",
     "gridPos": { "h": 4, "w": 9, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "fortigate_certificate_valid_to_seconds{instance=~\"[[firewall]]\",scope=~\"[[scope]]\",name=~\"[[certificate]]\"} *1000"
      }
     ]
    }
   ]
  },
  {
   "title": "SD-WAN",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Virtual WAN Status",
     "type": "graph",
     "gridPos": { "h": 5, "w": 7, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "fortigate_virtual_wan_status{instance=~\"[[firewall]]\", state=\"up\"} != 0\r",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "Virtual WAN Latency",
     "type": "graph",
     "gridPos": { "h": 5, "w": 7, "x": 7, "y": 18 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "fortigate_virtual_wan_latency_seconds{instance=~\"[[firewall]]\"}\r",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "Virtual WAN Sent / Received Total",
     "type": "graph",
     "gridPos": { "h": 5, "w": 7, "x": 15, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "fortigate_virtual_wan_packet_sent_total{instance=~\"[[firewall]]\"}\r",
       "legendFormat": "{{interface}} sent"
      },
      {
       "expr": "fortigate_virtual_wan_packet_received_total{instance=~\"[[firewall]]\"}",
       "legendFormat": "{{interface}} received"
      }
     ]
    },
    {
     "title": "[[sdwan]] State Change",
     "type": "stat",
     "gridPos": { "h": 2, "w": 7, "x": 0, "y": 23 },
     "repeat": "sdwan",
     "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "fortigate_virtual_wan_status_change_time_seconds{instance=~\"[[firewall]]\",interface=\"[[sdwan]]\"} *1000",
       "legendFormat": "{{sdwan}}"
      }
     ]
    },
    {
     "title": "Virtual WAN Jitter",
     "type": "graph",
     "gridPos": { "h": 5, "w": 7, "x": 7, "y": 23 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "fortigate_virtual_wan_latency_jitter_seconds{instance=~\"[[firewall]]\"}\r",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "Virtual WAN Active Sessions",
     "type": "graph",
     "gridPos": { "h": 5, "w": 7, "x": 15, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "fortigate_virtual_wan_active_sessions{instance=~\"[[firewall]]\"}\r",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "Virtual WAN Packet Loss",
     "type": "graph",
     "gridPos": { "h": 5, "w": 7, "x": 7, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "fortigate_virtual_wan_packet_loss_ratio{instance=~\"[[firewall]]\"}\r",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "[[sdwan]] Bandwidth",
     "type": "graph",
     "gridPos": { "h": 4, "w": 7, "x": 15, "y": 28 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "irate(fortigate_virtual_wan_bandwidth_tx_byte_per_second{instance=\"[[firewall]]\",interface=~\"[[sdwan]]\"}[1m]) * 8",
       "legendFormat": "{{interface}} TX"
      },
      {
       "expr": "irate(fortigate_virtual_wan_bandwidth_rx_byte_per_second{instance=\"[[firewall]]\",interface=~\"[[sdwan]]\"}[1m]) * 8\r",
       "legendFormat": "{{interface}} RX"
      }
     ]
    }
   ]
  },
  {
   "title": "HA Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Usage Ratio",
     "type": "graph",
     "gridPos": { "h": 4, "w": 7, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "fortigate_ha_member_cpu_usage_ratio{instance=~\"[[firewall]]\"} *100",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Sessions",
     "type": "graph",
     "gridPos": { "h": 4, "w": 7, "x": 7, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "fortigate_ha_member_sessions{instance=~\"[[firewall]]\"} *100",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": " Member Status",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 7, "x": 14, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "fortigate_ha_member_info{instance=~\"[[firewall]]\"}",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Network Usage Ratio",
     "type": "graph",
     "gridPos": { "h": 4, "w": 7, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "fortigate_ha_member_network_usage_ratio{instance=~\"[[firewall]]\"}",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Member Packets Total",
     "type": "graph",
     "gridPos": { "h": 4, "w": 7, "x": 7, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "fortigate_ha_member_packets_total{instance=~\"[[firewall]]\"} *100",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Virus Events Total",
     "type": "graph",
     "gridPos": { "h": 4, "w": 7, "x": 14, "y": 21 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "fortigate_ha_member_virus_events_total{instance=~\"[[firewall]]\"}",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "MEM Usage Ratio",
     "type": "graph",
     "gridPos": { "h": 4, "w": 7, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "fortigate_ha_member_memory_usage_ratio{instance=~\"[[firewall]]\"} *100",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Member BytesTotal",
     "type": "graph",
     "gridPos": { "h": 4, "w": 7, "x": 7, "y": 25 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "fortigate_ha_member_bytes_total{instance=~\"[[firewall]]\"} *100",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "IPS Events Total",
     "type": "graph",
     "gridPos": { "h": 4, "w": 7, "x": 14, "y": 25 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "fortigate_ha_member_ips_events_total{instance=~\"[[firewall]]\"}",
       "legendFormat": "{{hostname}}"
      }
     ]
    }
   ]
  }
 ]
}