FROM alpine:latest

ARG PB_VERSION={{ pocketbase_version }}

RUN apk add --no-cache \
    unzip \
    ca-certificates

# download and unzip PocketBase
# too lazy to do this properly, will only work on ARM for now since {{ ansible_architecture }} returns aarch64 & not arm64
ADD https://github.com/pocketbase/pocketbase/releases/download/v${PB_VERSION}/pocketbase_${PB_VERSION}_linux_arm64.zip /tmp/pb.zip
RUN unzip /tmp/pb.zip -d /pb/

# uncomment to copy the local pb_migrations dir into the image
# COPY ./pb_migrations /pb/pb_migrations

# uncomment to copy the local pb_hooks dir into the image
# COPY ./pb_hooks /pb/pb_hooks

EXPOSE 8080

# start PocketBase
CMD ["/pb/pocketbase", "serve", "--http=0.0.0.0:8080"]
