---

- name: Copy streaks-api source
  copy:
    src: "streaks-api"
    dest: "/home/{{ user_name }}/docker/"

- name: Deploy streaks-api
  docker_compose:
    project_src: /home/{{ user_name }}/docker/streaks-api
    state: present
    pull: true
    build: true
