---

- name: Create streaks-api directory
  file:
    path: /home/{{ user_name }}/docker/streaks-api
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0755

- name: Template docker-compose file to target
  template:
    src: "docker-compose.yml.j2"
    dest: "/home/{{ user_name }}/docker/streaks-api/docker-compose.yml"

- name: Deploy streaks-api
  docker_compose:
    project_src: /home/{{ user_name }}/docker/streaks-api
    state: present
    pull: true
