---
# tasks file for plex

#docker run \
#  --name=plex \
#  --net=host \
#  -e PUID=1000 \
#  -e PGID=1000 \
#  -e VERSION=docker \
#  -e PLEX_CLAIM="claim-TY9me5r8txn4ppUz7R92" \
#  -v /home/fish/docker/plex/lib:/config \
#  -v /stor/plex/shows:/tv \
#  -v /stor/plex/movies:/movies \
#  -v /stor/plex/anime:/anime \
#  -v /stor/plex/music:/music \
#  --restart unless-stopped \
#  -d \
#   linuxserver/plex:latest

- name: Create plex folder
  file:
    path: "/home/{{ user_name }}/docker/plex"
    state: directory

- name: Template docker-compose file
  template:
    src: docker-compose.yml.j2
    dest: /home/{{ user_name }}/docker/plex/docker-compose.yml

- name: Deploy plex stack
  docker_compose:
    project_src: /home/{{ user_name }}/docker/plex
    state: present
    pull: true
    #restarted: true

