---

- name: Create bonsai directory
  file:
    path: /home/{{ user_name }}/docker/bonsai
    state: directory

- name: Template docker-compose file
  template:
    src: "docker-compose.yml.j2"
    dest: "/home/{{ user_name }}/docker/bonsai/docker-compose.yml"

- name: Deploy bonsai stack
  docker_compose:
    project_src: /home/{{ user_name }}/docker/bonsai
    pull: true
    state: present
